spring:
  application:
    name: baba
  data:
    mongodb:
      uri: ${MONOGDB_URI}
      database: contestBell
      auto-index-creation: true

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${MAIL}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: false

app:
  base-url: ${BASE_URL}
  frontend-url: ${FRONTEND_URL}
  admin-secret: ${ADMIN_SECRET}

jwt:
  secret: ${SECRET}
  expiration: 86400000

clist:
  api-key: ${CLIST_API}
  username: ${CLIST_USER}

brevo:
  api-key: ${BREVO_API_KEY}
  sender-email: ${MAIL}
  sender-name: Sahil from ContestBell